
package vista.pacientes;

import controlador.PacienteControlador;
import javax.swing.table.DefaultTableModel;
import modelo.PacienteModelo;

public class Listado extends javax.swing.JInternalFrame {

    public DefaultTableModel tablemodel = new DefaultTableModel();
    PacienteControlador pc = PacienteControlador.getInstancia();
    
    public Listado() {
        initComponents();
        
        
        lbl_listado.setModel(tablemodel);
        String columnas[] = {"CEDULA", "NOMBRES","EDAD", "SEXO"};
        tablemodel.setColumnIdentifiers(columnas);
        
        cargarListadoPacientes();
    
    }
    
    private void cargarListadoPacientes(){
        for (PacienteModelo pm : pc.listadoCompleto()) {
            Object [] fila ={pm.getCedula(), pm.getNombre(), pm.getEdad(), pm.getSexo()};
            tablemodel.addRow(fila);
            
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txt_buscarcedula = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        lbl_listado = new javax.swing.JTable();

        jLabel1.setText("BUSCAR POR CEDULA ");

        txt_buscarcedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_buscarcedulaActionPerformed(evt);
            }
        });
        txt_buscarcedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_buscarcedulaKeyReleased(evt);
            }
        });

        lbl_listado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(lbl_listado);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(37, 37, 37)
                        .addComponent(txt_buscarcedula, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_buscarcedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_buscarcedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_buscarcedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_buscarcedulaActionPerformed

    private void txt_buscarcedulaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_buscarcedulaKeyReleased
        tablemodel.setRowCount(0);
        
        String cedula = txt_buscarcedula.getText();
        
        
        for (PacienteModelo pm : pc.listadoCompletoPorCedula(cedula)) {
            Object [] fila ={pm.getCedula(), pm.getNombre(), pm.getEdad(), pm.getSexo()};
            tablemodel.addRow(fila);
        }
    }//GEN-LAST:event_txt_buscarcedulaKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable lbl_listado;
    private javax.swing.JTextField txt_buscarcedula;
    // End of variables declaration//GEN-END:variables
}
